### ISSUE TITLE
Incompatiblity with Material UI v1

### ISSUE THREAD

**Issue by denisdifazio** [mattp94/react-easy-validation#1]
Hey, awesome package!

The problem is that Material UI v1 components TextFields, InputLabel, Input, etc all have an "error" property that is flagged true or false besides the "errorText", which now is called "helperText".

My suggestion is to add another optional prop in ValidationIn and ValidationOut components called "errorFlag" that works exactly as the "error" prop, where the user defines a property's name to set to true when the rules are not validated and vice-versa

**Comment by mattp94** [comment]
Thanks for your message! That's a very good idea, but Material-UI v1 is unfortunately still in beta. So I don't know if it's relevant to make this change now as it could be interesting to change default props as well.

**Comment by mario-zancanaro** [comment]
Hi!
The package is still incompatible with Material-UI V1 or we can have a work around to use with V1?

Thanks

**Comment by mattp94** [comment]
I'm currently working on a next version which will be compatible with Material-UI v1. I'll probably publish an alpha release next week.

**Comment by mattp94** [comment]
Hey @nanocreaator, I published it yesterday. Let's see [here](https://github.com/mattp94/react-easy-validation/tree/v2)!

**Comment by mario-zancanaro** [comment]
Great job! 👏🏻
I’ll check ASAP and post you back if I find some problem.
Thanks a lot for the update!
