### ISSUE TITLE
Let me clean up manually without the need to delete the dom

### ISSUE THREAD

**Issue by mrrinot** [mattp94/react-easy-validation#2]
<img width="795" alt="image" src="https://user-images.githubusercontent.com/22248411/44040545-e228d19c-9f1b-11e8-92e0-4cac3f0b1b8a.png">
 
In the AddButton's handle, I manually reset the values for the TextField and FileButton after validating.
The error text doesn't go away.

**Comment by lzientek** [comment]
Yes we also realy need that on our project!

**Comment by Telokis** [comment]
Please, this is a must-have! I can't picture my life without it!

**Comment by mattp94** [comment]
Good news, this feature is now available from [v2.1.0](https://github.com/mattp94/react-easy-validation/releases/tag/v2.1.0) and [v1.2.0](https://github.com/mattp94/react-easy-validation/releases/tag/v1.2.0) releases!
